const productos = [
    { codigo: 1, nombre: "Abrigo Impermeable para perro", img: "imgs/p1.webp", precio: { S: 89, M: 99, L: 109, XL: 129 }, stock: { S: 5, M: 5, L: 5, XL: 5 }, descripcion: "Mezcla un look retro para perritos amantes de los diseños divertidos."},
    { codigo: 2, nombre: "Chompa para perro Funky Retro", img: "imgs/p2.webp", precio: { S: 69, M: 74, L: 77, XL: 81 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 3, nombre: "Chompa para perro Velero Rojo", img: "imgs/p3.webp", precio: { S: 69, M: 72, L: 74, XL: 77 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 4, nombre: "Chompa para perro Eco Trenza Plomo Azulado", img: "imgs/p4.webp", precio: { S: 65, M: 67, L: 68, XL: 69 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 5, nombre: "Chompa para perro Rombo Fucsia", img: "imgs/p5.webp", precio: { S: 65, M: 70, L: 75, XL: 85 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 6, nombre: "Chompa para perro Chess", img: "imgs/p6.webp", precio: { S: 69, M: 73, L: 77, XL: 85 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 7, nombre: "Mr. Charlie Hoodie para perro", img: "imgs/p7.png", precio: { S: 55, M: 60, L: 63, XL: 65 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 8, nombre: "Chompa para perro Happy Hour", img: "imgs/p8.webp", precio: { S: 81, M: 81, L: 81, XL: 81 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 9, nombre: "Mint and Pink Stripes Hoodie para perro", img: "imgs/p9.webp", precio: { S: 55, M: 60, L: 63, XL: 65 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 10, nombre: "Green Stripes Hoodie para perro", img: "imgs/p10.webp", precio: { S: 55, M: 60, L: 63, XL: 65 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 11, nombre: "Chompa para perro Fried Eggs", img: "imgs/p11.webp", precio: { S: 69, M: 69, L: 69, XL: 69 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 12, nombre: "Chompa para perro Rombo Azul", img: "imgs/p12.webp", precio: { S: 65, M: 70, L: 75, XL: 85 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 13, nombre: "Chompa para perro Multicolor Stripes Orange", img: "imgs/p13.webp", precio: { S: 81, M: 81, L: 81, XL: 81 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 14, nombre: "Berry Fun Hoodie para perro", img: "imgs/p14.webp", precio: { S: 55, M: 55, L: 55, XL: 55 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 15, nombre: "Chompa para perro Piña Colada", img: "imgs/p15.webp", precio: { S: 69, M: 72, L: 74, XL: 77 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 16, nombre: "Chompa para perro Floral", img: "imgs/p16.webp", precio: { S: 69, M: 69, L: 69, XL: 69 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 17, nombre: "Chompa para perro Hearts", img: "imgs/p17.webp", precio: { S: 77, M: 77, L: 77, XL: 77 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 18, nombre: "Chompa para perro Army Camouflage", img: "imgs/p18.webp", precio: { S: 65, M: 70, L: 75, XL: 85 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 19, nombre: "Chompa para perro Eco Trenza Jean", img: "imgs/p19.webp", precio: { S: 65, M: 70, L: 75, XL: 81 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 20, nombre: "Chompa para perro Eco Trenza Celeste", img: "imgs/p20.webp", precio: { S: 65, M: 67, L: 68, XL: 69 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 21, nombre: "Chompa para perro Eco Trenza Rojo Rosa", img: "imgs/p21.png", precio: { S: 65, M: 67, L: 68, XL: 69 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 22, nombre: "Chompa para Perro Escocés", img: "imgs/p22.png", precio: { S: 65, M: 67, L: 70, XL: 73 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 23, nombre: "Baby Pink Stripes Hoodie para perro", img: "imgs/p23.png", precio: { S: 55, M: 58, L: 59, XL: 60 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 24, nombre: "Polo para perro Safari", img: "imgs/p24.png", precio: { S: 50, M: 52, L: 53, XL: 55 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 25, nombre: "Polo para perro Shark Tanktop", img: "imgs/p25.webp", precio: { S: 50, M: 52, L: 53, XL: 55 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 26, nombre: "Orca Hoodie para perro", img: "imgs/p26.jpg", precio: { S: 55, M: 60, L: 63, XL: 65 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 27, nombre: "Sky Wing Hoodie", img: "imgs/p27.png", precio: { S: 55, M: 57, L: 58, XL: 60 }, stock: { S: 5, M: 5, L: 5, XL: 5 } },
    { codigo: 28, nombre: "Comida para perros", precio: 12, img: "imgs/comida-perros.webp", stock: 50 },
    { codigo: 29, nombre: "Comida para gatos", precio: 10, img: "imgs/comida-gatos.webp", stock: 40 }
];